import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Toaster } from "@/components/ui/sonner"; // Importando o Toaster do Sonner

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Susurradores",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* pt-24 para mobile e md:pt-24 para desktop conforme seu comentário */}
        <main className="pt-24 md:pt-24">
          {children}
        </main>
        <Footer />
        
        <Toaster 
          theme="dark" 
          position="top-right" 
          richColors 
          closeButton
        />
      </body>
    </html>
  );
}